name: Convert FBX to VRM0.x with Blender

on:
  push:
    paths:
      - 'FBX/**/*.fbx'
      - '.github/workflows/convert-fbx-to-vrm.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fbx-to-vrm:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2) Blender をインストール
      - name: Install Blender
        run: |
          sudo apt-get update
          sudo apt-get install -y blender

      # 3) VRM Add‑on for Blender を取得
      - name: Clone VRM Add‑on
        run: |
          git clone https://github.com/saturday06/VRM-Addon-for-Blender.git blender_addons/VRM_Addon_for_Blender

      # 4) 変換用スクリプトを生成
      - name: Create conversion script
        run: |
          cat << 'EOF' > convert_fbx_to_vrm.py
          import bpy, os

          # アドオンをインストール＆有効化  [oai_citation:0‡github.com](https://github.com/saturday06/VRM-Addon-for-Blender?utm_source=chatgpt.com)
          addon_path = os.path.abspath("blender_addons/VRM_Addon_for_Blender")
          bpy.ops.preferences.addon_install(filepath=addon_path, overwrite=True)
          bpy.ops.preferences.addon_enable(module="io_scene_vrm")

          # 出力ディレクトリ準備
          out_dir = os.path.abspath("ExportedVRM")
          os.makedirs(out_dir, exist_ok=True)

          # FBX をすべてインポート→VRMエクスポート
          fbx_dir = os.path.abspath("FBX")
          for fname in os.listdir(fbx_dir):
              if not fname.lower().endswith(".fbx"):
                  continue
              fbxpath = os.path.join(fbx_dir, fname)
              # 新規シーン
              bpy.ops.wm.read_factory_settings(use_empty=True)
              # FBXインポート
              bpy.ops.import_scene.fbx(filepath=fbxpath)
              # VRMエクスポート
              basename = os.path.splitext(fname)[0]
              vrmpath = os.path.join(out_dir, basename + ".vrm")
              bpy.ops.export_scene.vrm(filepath=vrmpath)
          EOF

      # 5) Blender をバッチモードで実行 → FBX→VRM 変換
      - name: Run Blender conversion
        run: |
          blender --background \
                  --python convert_fbx_to_vrm.py

      # 6) 生成された VRM をコミット＆プッシュ
      - name: Commit & Push VRM files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ExportedVRM/
          if git diff --cached --quiet; then
            echo "✅ No new VRM files"
          else
            git commit -m "Auto-convert FBX → VRM"
            git push
          fi
