name: FBX → VRM Conversion & Commit

on:
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install FBX2glTF from Godot fork
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libstdc++6
          wget https://github.com/godotengine/FBX2glTF/releases/latest/download/FBX2glTF-linux-x86_64.zip -O fbx2gltf.zip
          unzip fbx2gltf.zip -d fbx2gltf
          sudo mv fbx2gltf/FBX2glTF-linux-x86_64/FBX2glTF /usr/local/bin/fbx2gltf
          chmod +x /usr/local/bin/fbx2gltf
        # 正しいバイナリ名とパス構成に修正 :contentReference[oaicite:0]{index=0}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: |
          npm init -y
          npm install @gltf-transform/core @gltf-transform/extensions @gltf-transform/functions @pixiv/three-vrm

      - name: Write conversion script
        run: |
          cat > convert.js << 'EOF'
          #!/usr/bin/env node
          import { spawnSync }    from 'child_process';
          import { NodeIO }       from '@gltf-transform/core';
          import { VRMExtension } from '@gltf-transform/extensions';
          import { VRM }          from '@pixiv/three-vrm';
          import fs               from 'fs';
          import path             from 'path';

          const [,, inputFbx, outputVrm] = process.argv;
          if (!inputFbx || !outputVrm) {
            console.error('Usage: node convert.js input.fbx output.vrm');
            process.exit(1);
          }

          const tmpGltf = path.join(process.cwd(), 'tmp.model.gltf');
          spawnSync('fbx2gltf', ['-i', inputFbx, '-o', tmpGltf], { stdio: 'inherit' });

          const io  = new NodeIO().registerExtensions([VRMExtension]);
          const doc = io.read(tmpGltf);
          VRM.from(doc.getRoot(), {
            meta: {
              name:             path.basename(inputFbx, '.fbx'),
              version:          '1.0.0',
              author:           'Automated CI',
              allowedUser:      'Everyone',
              violentUssage:    'Disallow',
              sexualUssage:     'Disallow',
              commercialUssage: 'Allow'
            }
          }).then(vrm => {
            vrm.write(outputVrm);
            fs.unlinkSync(tmpGltf);
            console.log('Exported:', outputVrm);
          });
          EOF
          chmod +x convert.js

      - name: Convert all FBX to VRM
        run: |
          mkdir -p outputs
          for f in *.fbx; do
            name=$(basename "$f" .fbx)
            node convert.js "$f" "outputs/${name}.vrm"
          done

      - name: Commit and Push VRM files
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add outputs/*.vrm
          git commit -m "chore: add converted VRM models" || echo "Nothing to commit"
          git push
