name: FBXからVRMへの変換（手動実行）

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'ダミーパラメータ（このワークフローは手動実行されます）'
        required: false

jobs:
  convert:
    runs-on: ubuntu-latest
    name: FBXファイルをglTFに変換し、VRM疑似ファイルを生成しリポジトリにコミットする

    steps:
      - name: リポジトリをチェックアウトする
        uses: actions/checkout@v3

      - name: unzipのインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: FBX2glTFツールのセットアップ
        run: |
          echo "FBX2glTFツール（v0.9.7）をダウンロードしています..."
          # 指定されたURLからFBX2glTF Linux版をダウンロードします
          curl -L -o FBX2glTF https://github.com/facebookincubator/FBX2glTF/releases/download/v0.9.7/FBX2glTF-linux-x64
          chmod +x FBX2glTF
          echo "FBX2glTFのダウンロードとセットアップが完了しました。"

      - name: FBXからglTFおよびVRM疑似変換処理開始
        run: |
          # 変換結果格納用ディレクトリの作成
          mkdir -p temp_gltf
          mkdir -p converted_vrm
          
          # リポジトリ内の全てのFBXファイルに対して変換処理を実施します
          for fbxf in $(find . -type f -name "*.fbx"); do
            filename=$(basename "$fbxf" .fbx)
            echo "ファイル '$fbxf' をglTF形式に変換中..."
            ./FBX2glTF "$fbxf" -o temp_gltf/"$filename".gltf

            if [ -f temp_gltf/"$filename".gltf ]; then
              echo "glTF変換成功: temp_gltf/$filename.gltf"
              # 注意: 本来はここでglTFをVRMに変換する処理が必要ですが、
              # 現在glTF2VRM等の対応ツールが存在しないため、代わりに
              # glTFファイルをVRM拡張子にリネーム（コピー）して疑似的にVRMファイルとして扱います。
              cp temp_gltf/"$filename".gltf converted_vrm/"$filename".vrm
              echo "VRM疑似ファイル生成完了: converted_vrm/$filename.vrm"
            else
              echo "エラー: '$fbxf' のglTF変換に失敗しました。"
            fi
          done

      - name: 生成されたVRM疑似ファイルをコミット
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # 変換されたVRM疑似ファイルをリポジトリのルートディレクトリにコピーします
          cp -r converted_vrm/* .
          git add $(find . -type f -name "*.vrm") || echo "VRMファイルが見つかりませんでした。"
          
          # 変更がある場合のみコミット・プッシュします
          if ! git diff-index --quiet HEAD --; then
            git commit -m "FBXから生成されたVRM（疑似）アバターを追加"
            git push
          else
            echo "コミット対象のVRMファイルはありません。"
          fi
