name: Convert FBX to VRM0.x with Blender

on:
  push:
    paths:
      - '**/*.fbx'
      - '.github/workflows/convert-fbx-to-vrm.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fbx-to-vrm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Blender
        run: |
          sudo apt-get update
          sudo apt-get install -y blender

      - name: Clone VRM Add‑on
        run: |
          git clone https://github.com/saturday06/VRM-Addon-for-Blender.git blender_addons

      - name: Install VRM Add‑on into Blender
        run: |
          # Blender ユーザーアドオンディレクトリにコピー
          mkdir -p $HOME/.config/blender/4.0/scripts/addons
          cp -r blender_addons/io_scene_vrm $HOME/.config/blender/4.0/scripts/addons/

      - name: Create conversion script
        run: |
          cat << 'EOF' > convert_fbx_to_vrm.py
          import bpy, os, sys

          # アドオン有効化
          bpy.ops.preferences.addon_enable(module="io_scene_vrm")

          # 出力先
          out_dir = os.path.abspath("ExportedVRM")
          os.makedirs(out_dir, exist_ok=True)

          # リポジトリ内の .fbx を再帰的に検索
          cwd = os.getcwd()
          for root, dirs, files in os.walk(cwd):
              for fname in files:
                  if not fname.lower().endswith(".fbx"):
                      continue
                  fbxpath = os.path.join(root, fname)
                  # 新規シーン
                  bpy.ops.wm.read_factory_settings(use_empty=True)
                  # FBX インポート
                  try:
                      bpy.ops.import_scene.fbx(filepath=fbxpath)
                  except Exception as e:
                      print(f"Failed to import {fbxpath}: {e}", file=sys.stderr)
                      continue
                  # VRM0.x エクスポート
                  basename = os.path.splitext(fname)[0]
                  vrmpath = os.path.join(out_dir, basename + ".vrm")
                  bpy.ops.export_scene.vrm(filepath=vrmpath)
                  print(f"Exported {vrmpath}")
          EOF

      - name: Run Blender conversion
        run: |
          blender --background --python convert_fbx_to_vrm.py

      - name: Commit & Push VRM files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ExportedVRM/
          if git diff --cached --quiet; then
            echo "✅ No new VRM files"
          else
            git commit -m "Auto-convert FBX → VRM"
            git push
          fi
