name: Convert FBX → VRM1.x with Metadata

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'VRM のタイトル'
        required: true
        default: 'MyAvatar'
      author:
        description: 'VRM の作者'
        required: true
        default: 'GitHub Actions Bot'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Download FBX2glTF binary
      run: |
        # v0.9.7 の Linux x64 バイナリを GitHub リリースから取得
        wget -qO FBX2glTF \
          https://github.com/facebookincubator/FBX2GLTF/releases/download/v0.9.7/FBX2glTF-linux-x64
        chmod +x FBX2glTF
      # リリース・バイナリの入手方法はコミュニティでも推奨されています :contentReference[oaicite:0]{index=0}

    - name: Install glTF-Transform tools
      run: |
        npm install @gltf-transform/cli @gltf-transform/core @gltf-transform/extensions

    - name: Convert FBX to GLB
      run: |
        mkdir -p temp_glb
        for f in FBX/**/*.fbx; do
          base=$(basename "$f" .fbx)
          echo "Converting $f → temp_glb/$base.glb"
          ./FBX2glTF --binary --input "$f" --output "temp_glb/$base"
        done
      # GitHub リリースのバイナリを直接実行することで、npm 経由で見つからない問題を解消します :contentReference[oaicite:1]{index=1}

    - name: Create glb-to-vrm1 script
      run: |
        cat << 'EOF' > convert_glb_to_vrm1.js
        #!/usr/bin/env node
        import fs from 'fs';
        import path from 'path';
        import { NodeIO } from '@gltf-transform/core';
        import { VRMC_vrm } from '@gltf-transform/extensions';

        async function main() {
          const title  = process.env.INPUT_TITLE  || 'Untitled';
          const author = process.env.INPUT_AUTHOR || 'Unknown';
          const io = new NodeIO().registerExtensions([VRMC_vrm]);
          const outDir = path.resolve('ExportedVRM1');
          fs.mkdirSync(outDir, { recursive: true });

          const files = fs.readdirSync('temp_glb').filter(f => f.endsWith('.glb'));
          for (const file of files) {
            const inPath = path.join('temp_glb', file);
            const doc    = io.read(inPath);
            const vrmExt = doc.createExtension(VRMC_vrm);
            const meta   = vrmExt.createMetadata();
            meta.setTitle(title);
            meta.setAuthor(author);
            const outPath = path.join(outDir, file.replace(/\.glb$/, '.vrm'));
            io.write(outPath, doc);
            console.log(`Exported VRM1.x → ${outPath}`);
          }
        }

        main().catch(err => {
          console.error(err);
          process.exit(1);
        });
        EOF
        chmod +x convert_glb_to_vrm1.js

    - name: Run glb-to-vrm1 conversion
      env:
        INPUT_TITLE:  ${{ github.event.inputs.title }}
        INPUT_AUTHOR: ${{ github.event.inputs.author }}
      run: |
        mkdir -p ExportedVRM1
        # 型変換だけ行いディレクトリ構成を作る
        npx gltf-transform copy temp_glb -o ExportedVRM1 --extension VRMC_vrm
        # 本スクリプトでメタデータ埋め込み＆書き出し
        node convert_glb_to_vrm1.js

    - name: Commit & Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ExportedVRM1/
        if git diff --cached --quiet; then
          echo "✅ No new VRM1.x files"
        else
          git commit -m "Auto-convert FBX → VRM1.x (Title: '${{ github.event.inputs.title }}', Author: '${{ github.event.inputs.author }}')"
          git push
        fi
